booking/protected/models/RoomInventory.php
<?php

Yii::import('application.models._base.BaseRoomInventory');

class RoomInventory extends BaseRoomInventory {

    private $username = "CONBMGSB";
    private $password = "guCe2utrubrewud";
    //private $domain = "https://stage.services.rccl.com";
    private $domain = "https://services.rccl.com";

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    /* Error format
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
      <soapenv:Body>
      <bo:retrieveBookingResponse xmlns:alpha="http://www.opentravel.org/OTA/2003/05/alpha" xmlns:bo="http://services.rccl.com/Interfaces/RetrieveBooking">
      <alpha:OTA_ResRetrieveRS Version="11">
      <alpha:Errors>
      <alpha:Error ShortText="HOSTERR" Type="11">Generic error occured.</alpha:Error>
      <alpha:Error ShortText="HOSTERR" Type="12">Generic error occured.</alpha:Error>
      </alpha:Errors>
      </alpha:OTA_ResRetrieveRS>
      </bo:retrieveBookingResponse>
      </soapenv:Body>
      </soapenv:Envelope>
     */

    public function retrieveBooking($reservationCode) {
        $xml = '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
				   <soap:Body>
				      <retrieveBooking xmlns="http://services.rccl.com/Interfaces/RetrieveBooking">
				         <OTA_ReadRQ Version="2" TransactionIdentifier="e6e7e93ddbe4449292f93d77bf81caf4" SequenceNmbr="2" RetransmissionIndicator="false" TransactionActionCode="RetrievePrice" xmlns="http://www.opentravel.org/OTA/2003/05/alpha">
				            <POS>
				               <Source ISOCurrency="HKD" TerminalID="12345">
				                  <RequestorID ID="331732" Type="5" ID_Context="AGENCY1"/>
				                  <BookingChannel Type="7">
				                     <CompanyName CompanyShortName="BMG"/>
				                  </BookingChannel>
				               </Source>
				            </POS>
				            <UniqueID Type="14" ID="' . $reservationCode . '"/>
				         </OTA_ReadRQ>
				      </retrieveBooking>
				   </soap:Body>
				</soap:Envelope>';
        //var_dump($xml);
		//CVarDumper::dump( $xml, 10, true);
        $result = $this->startSoap($xml, $this->domain . "/Reservation_FITWeb/sca/RetrieveBooking");
		//CVarDumper::dump( $result, 10, true);
		//exit();

        $return = array();
        if ($result["status"] === false) {
            $return["status"] = false;
            $return["message"] = "unknown";
        } else {
            $dom = simplexml_load_string($result["result"]);
            $success = $dom->children('soapenv', true)->Body->children('bo', true)->retrieveBookingResponse->children('alpha', true)->OTA_ResRetrieveRS->children('alpha', true);

            if (isset($success->Success)) {
                $return["status"] = true;
            } else {
                $return["status"] = false;
                $return["message"] = $success->Errors->children('alpha', true)->Error[0]->__toString();
            }
        }
        return $return;
    }

    public function makePayment($reservationCode, $type, $name, $cardNumber, $expire_year, $expire_month, $price) {
        $xml = '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
				   <soap:Body>
				      <makePayment xmlns="http://services.rccl.com/Interfaces/Payment">
				         <OTA_CruisePaymentRQ Version="1.2" TransactionIdentifier="e5d6a915dc3f4d82a9297c112469639d" SequenceNmbr="5" RetransmissionIndicator="false" xmlns="http://www.opentravel.org/OTA/2003/05/alpha">
				            <POS>
				               <Source ISOCurrency="HKD" TerminalID="12345">
				                  <RequestorID ID="331732" Type="5" ID_Context="AGENCY1"/>
				                  <BookingChannel Type="7">
				                     <CompanyName CompanyShortName="BMG"/>
				                  </BookingChannel>
				               </Source>
				            </POS>
				            <ReservationPayment>
				               <ReservationID Type="14" SyncDateTime="' . date("Y-m-d") . 'T' . date("H:i:s") . 'Z" ID="' . $reservationCode . '"/>
				               <PaymentDetail>
				                  <PaymentCard CardCode="' . $type . '" CardNumber="' . $cardNumber . '" ExpireDate="' . $expire_month . $expire_year . '">
				                     <CardHolderName>' . $name . '</CardHolderName>
				                  </PaymentCard>
				                  <PaymentAmount Amount="' . $price . '"/>
				               </PaymentDetail>
				            </ReservationPayment>
				         </OTA_CruisePaymentRQ>
				      </makePayment>
				   </soap:Body>
				</soap:Envelope>';
        //var_dump($xml);
        $result = $this->startSoap($xml, $this->domain . "/Reservation_FITWeb/sca/Payment");
        //var_dump($result);
        //exit();
        $return = array();
        if ($result["status"] === false) {
            $return["status"] = false;
            $return["message"] = "unknown";
        } else {
            $dom = simplexml_load_string($result["result"]);
            $payment = $dom->children('soapenv', true)->Body->children('pa', true)->makePaymentResponse->children('alpha', true)->OTA_CruisePaymentRS->children('alpha', true);
            $reservationID = $payment->ReservationPayment->children('alpha', true)->ReservationID->attributes()->ID;
            if (trim($reservationID) != "") {
                $return["status"] = true;
                $return["code"] = $payment->ReservationPayment->children('alpha', true)->PaymentDetail->children("alpha", true)->PaymentAmount->attributes()->ApprovalCode->__toString();
                $return["reservationID"] = $reservationID;
                $return["org_xml"] = $result["result"];
            } else {
                $return["status"] = false;
                $return["code"] = $payment->Warnings->children('alpha', true)->Warning[0]->attributes()->ShortText->__toString();
                $return["message"] = $payment->Warnings->children('alpha', true)->Warning[0]->__toString();
                $return["org_xml"] = $result["result"];
            }
        }
        return $return;
    }

    private function startSoap($xml, $url) {
        $header = array(
            "Content-type: text/xml;charset=\"utf-8\"",
            "Accept: text/xml",
            "Cache-Control: no-cache",
            "Pragma: no-cache",
            "SOAPAction: \"run\"",
            "Content-length: " . strlen($xml),
        );

        $soap_do = curl_init();
        curl_setopt($soap_do, CURLOPT_URL, $url);
        curl_setopt($soap_do, CURLOPT_CONNECTTIMEOUT, 10);
        curl_setopt($soap_do, CURLOPT_TIMEOUT, 10);
        curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($soap_do, CURLOPT_POST, true);
        curl_setopt($soap_do, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
        curl_setopt($soap_do, CURLOPT_USERPWD, $this->username . ":" . $this->password);
        curl_setopt($soap_do, CURLOPT_POSTFIELDS, $xml);
        curl_setopt($soap_do, CURLOPT_HTTPHEADER, $header);
        $result = curl_exec($soap_do);

        if ($result === false) {
            $err = 'Curl error: ' . curl_error($soap_do);
            //print $err;
            curl_close($soap_do);
            return array(
                'status' => false,
                "result" => $err
            );
        } else {
            //echo $result;
            curl_close($soap_do);
            return array(
                'status' => true,
                "result" => $result
            );
        }
    }

}

booking/protected/controllers/ItineraryController.php
<?php

class ItineraryController extends GxController {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('serviceGetItineraries'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('index', 'view', 'create', 'update', 'upload', 'serviceGetAllRoomType', 'serviceCreateRoomTypePrice', 'serviceUpdateRoomTypePrice', 'serviceDeleteRoomTypePrice', 'serviceloadAvailableRoomID'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin'),
                'users' => array('rcc_editor'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id, 'Itinerary'),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Itinerary;

        // Uncomment the following line if AJAX validation is needed
        //$this->performAjaxValidation($model);
        //echo realpath(Yii::app()->basePath ).'<br/>';
        //echo realpath(Yii::app()->basePath . '/../images').'<br/>';
        //echo '================================<br/>';
        //echo Yii::app()->params->upload_PDFPath.'<br/>';
        //echo realpath(Yii::app()->params->upload_PDFPath);

        if (isset($_POST['Itinerary'])) {

            //$model->attributes = $_POST['Itinerary'];
            $model->setAttributes($_POST['Itinerary']);

            //If you are only new to Yii and not in PHP, than you may know that uploaded files goes via $_FILES global variable 
            //and not via $_POST global variable. So to get uploaded file, you use  CUploadedFile::getInstance
            //$model->image = CUploadedFile::getInstance($model, 'image');
            //$model->pdf = CUploadedFile::getInstance($model, 'pdf');

            $model->setAttribute('image', $_POST['Itinerary']['image']);
            $model->setAttribute('pdf', $_POST['Itinerary']['pdf']);
            $model->setAttribute('create_time', strtotime("now"));
            
            /*
            $model->image = $_POST['Itinerary']['image'];
            $model->pdf = $_POST['Itinerary']['pdf'];
            $model->create_time = time();
            */
            //CVarDumper::dump($model, 10, true);
            if ($model->save()) {
                /*
                  if (!is_null($model->image)) {
                  $model->image->saveAs(realpath(Yii::app()->params->upload_ImagePath) . '/' . $model->image);
                  }
                  if (!is_null($model->pdf)) {
                  $model->pdf->saveAs(realpath(Yii::app()->params->upload_PDFPath) . '/' . $model->pdf);
                  }
                 */
                $this->redirect(array('update', 'id' => $model->itinerary_id));
            } else {
                Yii::log("errors saving SomeModel: " . var_export($model->getErrors(), true), CLogger::LEVEL_WARNING, __METHOD__);
            }
        }

        
        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {

        $model = $this->loadModel($id, 'Itinerary');
        //unlink(dirname(__FILE__) . DIRECTORY_SEPARATOR . '../../' . $model->image);
        // Uncomment the following line if AJAX validation is needed
        //$this->performAjaxValidation($model);
        //Yii::app()->end();
        // 10 is the default depth, and passing true will enable highlighting

        if (isset($_POST['Itinerary'])) {

            //$model->attributes = $_POST['Itinerary'];
            //$model->image = CUploadedFile::getInstance($_POST['Itinerary']['image'], 'image');
            //$model->pdf = CUploadedFile::getInstance($_POST['Itinerary']['pdf'], 'pdf');

            if (!empty($_POST['Itinerary']['image']) != $model->image && !empty($model->image)) {
                $file_path = dirname(__FILE__) . DIRECTORY_SEPARATOR . '../../' . str_replace(Yii::app()->getBaseUrl(true) . '/', '', $model->image);
                if (!is_dir($file_path) && file_exists($file_path)) {
                    unlink($file_path);
                }
                //$model->image = $_POST['Itinerary']['image'];
                $model->setAttribute('image', $_POST['Itinerary']['image']);
            }
            if (!empty($_POST['Itinerary']['pdf']) != $model->pdf && !empty($model->pdf)) {
                $file_path = dirname(__FILE__) . DIRECTORY_SEPARATOR . '../../' . str_replace(Yii::app()->getBaseUrl(true) . '/', '', $model->pdf);
                if (!is_dir($file_path) && file_exists($file_path)) {
                    unlink($file_path);
                }
                //$model->pdf = $_POST['Itinerary']['pdf'];
                $model->setAttribute('pdf', $_POST['Itinerary']['pdf']);
            }


            //$model->image = CUploadedFile::getInstance($model, 'image');
            //$model->pdf = CUploadedFile::getInstance($model, 'pdf');
            //$model->start_date = CDateTimeParser::parse($model->start_date, Yii::app()->params->dateFormat['long']);
            //$model->end_date = CDateTimeParser::parse($model->end_date, Yii::app()->params->dateFormat['long']);
            //$model->update_time = time();
            $model->setAttribute('update_time', time());
            //$old_itinerary_id = $model->itinerary_id;
			$old_itinerary_id = $id;
            
            $model->setAttributes($_POST['Itinerary'], false);

			/*
              CVarDumper::dump($old_itinerary_id, 10, true);
              CVarDumper::dump($_POST['Itinerary'], 10, true);
              exit();
			*/
            
            if ($model->save()) {

                if ($old_itinerary_id != $_POST['Itinerary']['itinerary_id']) {

					ItineraryRoomType::model()->updateAll(
                            array(
                        'itinerary_id' => $model->itinerary_id
                            )
                            , 'itinerary_id="' . $old_itinerary_id . '"'
                    );
					
					
                    RoomInventory::model()->updateAll(
                            array(
                        'itinerary_id' => $model->itinerary_id
                            )
                            , 'itinerary_id="' . $old_itinerary_id . '"'
                    );
                }
                //if ($model->save(true, array('itinerary_name', 'days_nights_full_desc', 'days_nights_short_desc', 'minimum_cruise_fares', 'language', 'start_date', 'end_date'))) {

                /*
                  if (!is_null($model->image)) {
                  if ($model->save(true, array('image'))) {
                  //$model->image->saveAs(realpath(Yii::app()->params->upload_ImagePath) . '/' . $model->image);
                  } else {
                  $update_successful = false;
                  }
                  }

                  if (!is_null($model->pdf)) {
                  if ($model->save(true, array('pdf'))) {
                  //$model->pdf->saveAs(realpath(Yii::app()->params->upload_PDFPath) . '/' . $model->pdf);
                  } else {
                  $update_successful = false;
                  }
                  }
                  if ($update_successful) {
                  } */
                $this->redirect(array('view', 'id' => $model->itinerary_id));
            } else {
                Yii::log("errors saving SomeModel: " . var_export($model->getErrors(), true), CLogger::LEVEL_WARNING, __METHOD__);
            }
        }

        $bookingRecord = Booking::model()->countByAttributes(
                array(
                    'itinerary_id' => $id,
                )
        );
		
		$InventoryRecord = RoomInventory::model()->countByAttributes(
                array(
                    'itinerary_id' => $id,
                )
        );
		
		$anyrecord = 0;
		if( count($bookingRecord) || count($InventoryRecord) ){
		
			$anyrecord = 1;
		}
		
        $this->render('update', array(
            'model' => $model,
            'bookingRecord' => $anyrecord,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {

booking/protected/views/roomInventory/_form.php
<?php
//public static registerScript(string $id, string $script, integer $position=NULL, array $htmlOptions=array ( ))
Yii::app()->clientScript->registerScript('search', "
        $('#queryString_btn').click(function (event) {

            //event.preventDefault();
            roomInventory_itinerary_id = $('#RoomInventory_itinerary_id').val();
            roomInventory_rt_id = $('#RoomInventory_rt_id').val();
            
                
            if( roomInventory_itinerary_id === '' ||  roomInventory_rt_id === '' ){
                event.preventDefault();
                alert('Please select a itinerary and room type first!'); 
            }else{
                
                href = $(this).attr('data-defaultLink') + '?itinerary_id=' + roomInventory_itinerary_id + '&rt_id=' + roomInventory_rt_id;
                
                $(this).attr('href', href);
                //console.log(href);
            }
        });
        
    var button = $('input#importStep1'), interval;
    
    $.ajax_upload(button, {
        action : uploadActionPath,
        name : 'myfile',
        onComplete : function(self, response) {
            //this.enable();
            //console.log(response);
            alert('File: ' + self + ' update successfully! \\n' + response);
        },
        onError : function(file, ext) {
            //this.disable();
            //alert(file);
            //console.log('efg');
        }
      
    });

");
?>

<div class="form">
    <?php
    $form = $this->beginWidget('GxActiveForm', array(
        'id' => 'room-inventory-form',
        'enableAjaxValidation' => false,
    ));
    ?>


    <div>
        <p class="note"  style="float:left">
            <?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
        </p>



        <div style="float:right;   padding: 5px 10px;   background-color: rgb(226, 228, 255);">
            <?php
            echo CHtml::link('Excel Template Download', Yii::app()->createUrl('roomInventory/serviceDownloadTemplate'), array('id' => 'queryString_btn', 'target' => '_blank', 'data-defaultLink' => Yii::app()->createUrl('roomInventory/serviceDownloadTemplate')))
            ?>
        </div>
        <div style="float:right;   padding: 5px 10px;   background-color: rgb(226, 228, 255); margin-right: 10px;">
            <?php //echo CHtml::button(Yii::t('importcsvModule.importcsv', 'Select CSV File'), array("id" => "importStep1")); ?>
            <?php echo CHtml::button(Yii::t('importcsv', 'Select CSV File'), array("id" => "importStep1")); ?>
        </div>
        <br style="clear:both;"/>
    </div>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo $form->labelEx($model, 'itinerary_id'); ?>
        <?php
        echo $form->dropDownList($model, 'itinerary_id', GxHtml::listDataEx(Itinerary::model()->findAllAttributes(array('itinerary_id', 'itinerary_name'), true), 'itinerary_id', array('itinerary_id', 'itinerary_name')), array(
            'prompt' => 'Select an itinerary',
            'ajax' => array(
                'type' => 'POST',
                'url' => Yii::app()->createUrl('Itinerary/ServiceLoadAvailableRoomID'), //or $this->createUrl('loadcities') if '$this' extends CController
                'update' => '#RoomInventory_rt_id', //or 'success' => 'function(data){...handle the data in the way you want...}',
                'data' => array('itinerary_id' => 'js:this.value'),
            ))
        );
        ?>
        <?php echo $form->error($model, 'itinerary_id'); ?>
    </div><!-- row -->
    <div class="row">
        <?php echo $form->labelEx($model, 'rt_id'); ?>
        <?php
        //echo $model->rt_id;
        ?>
        <?php
        //echo $form->dropDownList($model, 'rt_id', GxHtml::listDataEx(RoomType::model()->findAllAttributes(null, true)), array(
        $data_roomType = array();
        if (!$model->isNewRecord) {

            $data_roomType = GxHtml::listDataEx(RoomType::model()->findAllAttributes(null, true));
            //$data_roomType = GxHtml::listDataEx(RoomType::model()->findAllAttributes(array('rt_id', 'rt_name'), true));


            foreach ($data_roomType as $label => &$title) {
                $roomType = RoomType::model()->find('rt_id=:rt_id', array(':rt_id' => $title));
				//CVarDumper::dump($roomType);
                //$title = $label . ': ' .$roomType->rt_name;
                $title = $roomType->rt_id . ': ' .$roomType->rt_name;
            }
        }
        echo $form->dropDownList($model, 'rt_id', $data_roomType, array(
            'empty' => '-- Please select an itinerary --')
        );
        ?>
        <?php echo $form->error($model, 'rt_id'); ?>
    </div><!-- row -->
    <div class="row">
        <?php echo $form->labelEx($model, 'room_no'); ?>
        <?php echo $form->textField($model, 'room_no', array('maxlength' => 64)); ?>
        <?php echo $form->error($model, 'room_no'); ?>
    </div><!-- row -->
    <div class="row">

        <?php
        if (!$model->isNewRecord && is_null($model->update_time)) {
            echo $form->labelEx($model, 'update_time');
            echo Yii::app()->getDateFormatter()->format(Yii::app()->params->dateFormat["long_time"], $model->update_time);
            //echo $form->textField($model, 'update_time', array('readonly' => true));
            //echo $form->textField($model, 'update_time', array('readonly' => true));
            //echo $form->textField($model, 'update_time', array('readonly' => true,  'value' => Yii::app()->getDateFormatter( )->format(Yii::app()->params->dateFormat["long_time"], $model->update_time)));
            //echo $form->error($model, 'update_time');
        }
        ?>
    </div><!-- row -->
    <div class="row">

        <?php
        if (!$model->isNewRecord && is_null($model->booking_ip)) {
            echo $form->labelEx($model, 'booking_ip');
            echo $model->booking_ip;
            //echo $form->textField($model, 'booking_ip', array('readonly' => true));
            //echo $form->error($model, 'booking_ip');
        }
        ?>
    </div><!-- row -->
    <div class="row">
        <?php echo $form->labelEx($model, 'status'); ?>
        <?php echo $form->dropDownList($model, 'status', array('available' => 'available', 'payment_successful' => 'payment_successful')); ?>
        <?php echo $form->error($model, 'status'); ?>
    </div><!-- row -->
    <div class="row">
        <?php echo $form->labelEx($model, 'reservation_code'); ?>
        <?php echo $form->textField($model, 'reservation_code', array('maxlength' => 20)); ?>
        <?php echo $form->error($model, 'reservation_code'); ?>
    </div><!-- row -->
    <div class="row">
        <?php echo $form->labelEx($model, 'notes'); ?>
        <?php
        Yii::app()->royalCaribbeanHelper->echoTinyMCE($model, 'notes');
        ?>
        <?php echo $form->error($model, 'notes'); ?>
    </div><!-- row -->


    <?php
    echo GxHtml::submitButton(Yii::t('app', 'Save'));
    $this->endWidget();
    ?>
</div><!-- form -->

booking/protected/views/roomInventory/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('room_inventory_id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->room_inventory_id), array('view', 'id' => $data->room_inventory_id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('itinerary_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->itinerary)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('rt_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->rt)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('room_no')); ?>:
	<?php echo GxHtml::encode($data->room_no); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('update_time')); ?>:
	<?php echo GxHtml::encode($data->update_time); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('booking_ip')); ?>:
	<?php echo GxHtml::encode($data->booking_ip); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('status')); ?>:
	<?php echo GxHtml::encode($data->status); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('reservation_code')); ?>:
	<?php echo GxHtml::encode($data->reservation_code); ?>
	<br />
	<?php /*
	<?php echo GxHtml::encode($data->getAttributeLabel('notes')); ?>:
	<?php echo GxHtml::encode($data->notes); ?>
	<br />
	*/ ?>

</div>

booking/protected/views/roomInventory/view.php
<?php
$this->breadcrumbs = array(
    $model->label(2) => array('admin'),
    GxHtml::valueEx($model),
);

$this->menu = array(
    array('label' => Yii::t('app', 'List') . ' ' . $model->label(2), 'url' => array('index')),
    array('label' => Yii::t('app', 'Create') . ' ' . $model->label(), 'url' => array('create')),
    array('label' => Yii::t('app', 'Update') . ' ' . $model->label(), 'url' => array('update', 'id' => $model->room_inventory_id)),
    //array('label' => Yii::t('app', 'Delete') . ' ' . $model->label(), 'url' => '#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->room_inventory_id), 'confirm' => 'Are you sure you want to delete this item?')),
    array('label' => Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url' => array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
/*
CVarDumper::dump($model->rt, 10, true);
CVarDumper::dump($model->rt->rt_name, 10, true);
*/
$this->widget('zii.widgets.CDetailView', array(
    'data' => $model,
    'attributes' => array(
        'room_inventory_id',
        array(
            'name' => 'itinerary',
            'type' => 'raw',
            'value' => $model->itinerary !== null ? GxHtml::link(GxHtml::encode($model->itinerary->itinerary_id. ': '. $model->itinerary->itinerary_name), array('itinerary/view', 'id' => GxActiveRecord::extractPkValue($model->itinerary, true))) : null,
        //    'value' => $model->itinerary !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->itinerary)), array('itinerary/view', 'id' => GxActiveRecord::extractPkValue($model->itinerary, true))) : null,
        ),
        array(
            'name' => 'rt',
            'type' => 'raw',
            'value' => $model->rt !== null ? GxHtml::link(GxHtml::encode($model->rt->rt_id. ': '. $model->rt->rt_name), array('roomType/view', 'id' => GxActiveRecord::extractPkValue($model->rt, true))) : null,
            //'value' => $model->rt !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->rt)), array('roomType/view', 'id' => GxActiveRecord::extractPkValue($model->rt, true))) : null,
        ),
        'room_no',
        array(
            'name' => 'update_time',
            'value' => Yii::app()->getDateFormatter()->format(Yii::app()->params->dateFormat["long_time"], $model->update_time)
        ),
        'booking_ip',
        'reservation_code',
        'status',
        'notes',
    ),
));
?>