system/testdrive-bk/protected/controllers/CruiseController.php
<?php

class CruiseController extends GxController {

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function filters() {
        return array(
            'accessControl',
        );
    }

    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'upload'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin'),
                'users' => array('rcc_editor'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id, 'Cruise'),
        ));
    }

    public function actionCreate() {
        $model = new Cruise;


        if (isset($_POST['Cruise'])) {
            $model->setAttributes($_POST['Cruise']);

            if ($model->save()) {
                $model->create_time = time();
                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
                else
                    $this->redirect(array('view', 'id' => $model->cruise_id));
            }
        }

        $this->render('create', array('model' => $model));
    }

    public function actionUpdate($id) {
        $model = $this->loadModel($id, 'Cruise');


        if (isset($_POST['Cruise'])) {

            $old_cruise_id = $model->cruise_id;
            $model->setAttributes($_POST['Cruise']);
            if ($model->save()) {


                if ($old_cruise_id != $_POST['Cruise']['cruise_id']) {
                    RoomType::model()->updateAll(
                            array(
                        'cruise_id' => $_POST['Cruise']['cruise_id']
                            )
                            , 'cruise_id="' . $id . '"'
                    );

                    Itinerary::model()->updateAll(
                            array(
                        'cruise_id' => $_POST['Cruise']['cruise_id']
                            )
                            , 'cruise_id="' . $id . '"'
                    );
                    ItineraryRoomType::model()->updateAll(
                            array(
                        'cruise_id' => $_POST['Cruise']['cruise_id']
                            )
                            , 'cruise_id="' . $id . '"'
                    );
                }

                $this->redirect(array('view', 'id' => $model->cruise_id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionDelete($id) {

        if (Yii::app()->getRequest()->getIsPostRequest()) {
            $this->loadModel($id, 'Cruise')->delete();

            if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('admin'));
        } else {
            throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
        }
    }

    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Cruise');
        $dataProvider->sort->defaultOrder = 'update_time DESC';
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionAdmin() {
        $model = new Cruise('search');
        $model->unsetAttributes();

        if (isset($_GET['Cruise']))
            $model->setAttributes($_GET['Cruise']);

        $this->render('admin', array(
            'model' => $model,
        ));
    }

}

system/testdrive-bk/protected/controllers/GuestController.php
<?php

class GuestController extends GxController {

    public $layout = '//layouts/column1';
    
    public function filters() {
        return array(
            'accessControl',
        );
    }

    public function accessRules() {
        return array(
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('index', 'view','create', 'update', 'upload'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin'),
                'users' => array('rcc_editor'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }
    
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id, 'Guest'),
        ));
    }

    public function actionCreate() {
        $model = new Guest;


        if (isset($_POST['Guest'])) {
			
            $model->setAttributes($_POST['Guest']);
            $model->setAttribute('date_of_birth', CDateTimeParser::parse($model->date_of_birth, Yii::app()->params->dateFormat['long']));
			

            if ($model->save()) {
                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
                else
                    $this->redirect(array('view', 'id' => $model->guest_id));
            }
        }

        $this->render('create', array('model' => $model));
    }

    public function actionUpdate($id) {
        $model = $this->loadModel($id, 'Guest');


        if (isset($_POST['Guest'])) {
			
			
            $model->setAttributes($_POST['Guest']);
            $model->setAttribute('date_of_birth', CDateTimeParser::parse($model->date_of_birth, Yii::app()->params->dateFormat['long']));
			
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->guest_id));
            }
        }

   
          $itineraryRoomType_Model = ItineraryRoomType::model()->with('rt')->find(
          array(
          //'condition' => 'language="' . Yii::app()->params->language . '"',
          'condition' => 't.irt_id="' . $model->irt_id . '"',
          'limit' => 1
          )); 
     /*
        $model_ItineraryRoomType = ItineraryRoomType::model();
        $criteria = new CDbCriteria;
        $criteria->compare('irt_id', $model->irt_id);
        $criteria->with = array('rt');

        $itineraryRoomType_Model = new CActiveDataProvider(
                get_class($model_ItineraryRoomType), array(
            'criteria' => $criteria,
                )
        );*/

        //CVarDumper::dump($itineraryRoomType_Model, 10, true);

        $this->render('update', array(
            'model' => $model,
            'itineraryRoomType_Model' => $itineraryRoomType_Model,
        ));
    }

    public function actionDelete($id) {
        if (Yii::app()->getRequest()->getIsPostRequest()) {
            $this->loadModel($id, 'Guest')->delete();

            if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('admin'));
        } else
            throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
    }

    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Guest');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionAdmin() {
        $model = new Guest('search');
        $model->unsetAttributes();
        $model->dbCriteria->order='guest_id DESC';

        if (isset($_GET['Guest']))
            $model->setAttributes($_GET['Guest']);

        $this->render('admin', array(
            'model' => $model,
        ));
    }

}

system/testdrive-bk/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

system/testdrive-bk/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

system/testdrive-bk/protected/views/layouts/mail.php
<html>
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="content-type">
</head>
<body>
<table cellspacing="0" cellpadding="10" style="color:#666;font:13px Arial;line-height:1.4em;width:100%;">
	<tbody>
		<tr>
            <td>
				<?php echo $content ?>
            </td>
		</tr>
	</tbody>
</table>
</body>
</html>

system/testdrive-bk/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="language" content="en">
        
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/images/favicon.ico" rel="shortcut icon" type="image/x-icon">

        <!-- blueprint CSS framework -->
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
        <!--[if lt IE 8]>
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
        <![endif]-->

        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">

        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    </head>

    <body>

        <div class="container" id="page">

            <div id="header">
                <div id="logo">

                    <?php echo CHtml::link('<img src="' . Yii::app()->request->baseUrl . '/images/icons/logo.png" />', Yii::app()->request->baseUrl); ?><br/>
                    <?php echo CHtml::encode(Yii::app()->name); ?>
                </div>
            </div><!-- header -->

            <div id="mainmenu">
                <?php
                //'label'=>Yii::t('Login'),  可以試下用尼個!!!
                $this->widget('zii.widgets.CMenu', array(
                    'activeCssClass' => 'active',
                    'activateParents' => true,
                    'items' => array(
                        array('label' => 'Home', 'url' => array('/site/index'), 'visible' => !Yii::app()->user->isGuest),
                        array('label' => 'Bookings & Inventories',
                            'items' => array(
                                array('label' => 'Bookings', 'url' => array('/booking/admin')),
                                array('label' => 'Guests', 'url' => array('/guest/admin')),
                                array('label' => 'Stateroom Inventories', 'url' => array('/roomInventory/admin')),
                            ), 'visible' => !Yii::app()->user->isGuest),
                        array('label' => 'Itineraries',
                            'items' => array(
                                array('label' => 'Manage Itineraries', 'url' => array('/itinerary/admin')),
                                //array('label' => 'Itinerary Room Price', 'url' => array('/itineraryRoomType/index')),
                                array('label' => 'Promotional Codes', 'url' => array('/promotionCode/admin')),
                            //array('label' => 'Room type Promotion Code', 'url' => array('/roomtypePromotioncode/index')),
                            ), 'visible' => !Yii::app()->user->isGuest),
                        array('label' => 'Cruises',
                            'items' => array(
                                array('label' => 'Manage Cruises', 'url' => array('/cruise/admin')),
                                array('label' => 'Stateroom Categories', 'url' => array('/roomType/index')),
                            ), 'visible' => !Yii::app()->user->isGuest),
                        /*
                          array('label' => 'Download Excel',
                          'items' => array(
                          array('label' => 'Booking', 'url' => array('/booking/DownloadExcel')),
                          //array('label' => 'Stateroom Cats.', 'url' => array('/roomType/index')),
                          ), 'visible' => !Yii::app()->user->isGuest),
                         */
                        array('label' => 'Reservation code', 'url' => array('/reservationCode/admin'), 'visible' => !Yii::app()->user->isGuest),
                        //array('label' => 'Import CSV', 'url' => array('/importcsv'), 'visible' => !Yii::app()->user->isGuest),
                        //array('label' => 'About', 'url' => array('/site/page', 'view' => 'about'), 'visible' => !Yii::app()->user->isGuest),
                        //array('label' => 'Contact', 'url' => array('/site/contact'), 'visible' => !Yii::app()->user->isGuest),
                        array('label' => 'Login', 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
                        array('label' => 'Logout (' . Yii::app()->user->name . ')', 'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest)
                    ),
                ));
                ?>
            </div><!-- mainmenu -->
            <?php if (isset($this->breadcrumbs)): ?>
                <?php
                $this->widget('zii.widgets.CBreadcrumbs', array(
                    'links' => $this->breadcrumbs,
                    'homeLink' => false // add this line
                ));
                ?><!-- breadcrumbs -->
            <?php endif ?>

            <?php echo $content; ?>

            <div class="clear"></div>

            <div id="footer">
                Copyright &copy; <?php echo date('Y'); ?> by fevaworks.<br/>
                All Rights Reserved.<br/>
                <?php //echo Yii::powered();  ?>
            </div><!-- footer -->

        </div><!-- page -->

        <!--<script src="<?php echo Yii::app()->request->baseUrl; ?>/assets/js/jquery-ui.min.js"></script>-->
    </body>
</html>